/**
 * intercom:discover — Auto-discovers all Intercom workspace configuration
 * and writes/updates the backend .env file with the discovered values.
 *
 * Usage: npx ts-node --transpile-only src/scripts/intercom-discover.ts
 *
 * Requires INTERCOM_ACCESS_TOKEN to be set in .env or the shell environment.
 */

import 'dotenv/config';
import axios, { AxiosInstance } from 'axios';
import fs from 'fs';
import path from 'path';

const TOKEN = process.env.INTERCOM_ACCESS_TOKEN;
if (!TOKEN) {
  console.error('\n❌ INTERCOM_ACCESS_TOKEN is not set.');
  console.error('   Set it in .env or export it before running this script.');
  process.exit(1);
}

// ─── Intercom API client ─────────────────────────────────────────────────────

const api: AxiosInstance = axios.create({
  baseURL: 'https://api.intercom.io',
  headers: {
    Authorization: `Bearer ${TOKEN}`,
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'Intercom-Version': '2.11',
  },
  timeout: 15_000,
});

// ─── Types ───────────────────────────────────────────────────────────────────

interface TicketType {
  id: string;
  name: string;
  description: string;
  icon: string;
  archived: boolean;
  ticket_type_attributes?: TicketAttribute[];
}

interface TicketAttribute {
  id: string;
  name: string;
  data_type: string;
  required_to_create: boolean;
  required_to_create_for_contacts: boolean;
  description?: string;
  allowed_values?: string[];
}

interface Inbox {
  id: string;
  name: string;
  type: string;
}

interface Team {
  id: string;
  name: string;
}

interface Workspace {
  id: string;
  name: string;
  region: string;
  timezone: string;
  created_at: number;
}

interface ConversationAttribute {
  id: string;
  name: string;
  full_name: string;
  label: string;
  data_type: string;
  description?: string;
  options?: Array<{ value: string }>;
}

// ─── Discovery helpers ───────────────────────────────────────────────────────

async function getWorkspace(): Promise<Workspace> {
  const res = await api.get('/me');
  return res.data.app ?? res.data;
}

async function validateToken(): Promise<{ admin_id: string; name: string; email: string }> {
  const res = await api.get('/me');
  return {
    admin_id: res.data.id,
    name: res.data.name,
    email: res.data.email,
  };
}

async function getTicketTypes(): Promise<TicketType[]> {
  const res = await api.get('/ticket_types');
  return res.data.data ?? res.data.ticket_types ?? [];
}

async function getTicketTypeAttributes(ticketTypeId: string): Promise<TicketAttribute[]> {
  try {
    const res = await api.get(`/ticket_types/${ticketTypeId}`);
    return res.data.ticket_type_attributes?.data ?? res.data.ticket_type_attributes ?? [];
  } catch {
    return [];
  }
}

async function getTeams(): Promise<Team[]> {
  const res = await api.get('/teams');
  return res.data.teams ?? [];
}

async function getConversationAttributes(): Promise<ConversationAttribute[]> {
  try {
    const res = await api.get('/data_attributes?model=conversation');
    return res.data.data ?? [];
  } catch {
    return [];
  }
}

async function getContactAttributes(): Promise<ConversationAttribute[]> {
  try {
    const res = await api.get('/data_attributes?model=contact');
    return res.data.data ?? [];
  } catch {
    return [];
  }
}

// Intercom doesn't have a public /inboxes endpoint — inboxes live inside teams
// and the assignment rules API. We read them from teams + admin list.
async function getAdmins(): Promise<Array<{ id: string; name: string; email: string }>> {
  try {
    const res = await api.get('/admins');
    return res.data.admins ?? [];
  } catch {
    return [];
  }
}

// ─── .env read/write ─────────────────────────────────────────────────────────

function readEnv(envPath: string): Record<string, string> {
  if (!fs.existsSync(envPath)) return {};
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  const env: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

function writeEnv(envPath: string, env: Record<string, string>, comments: Record<string, string> = {}): void {
  const lines: string[] = [
    '# Loggro Incidents Portal — auto-generated by intercom:discover',
    `# Updated: ${new Date().toISOString()}`,
    '',
  ];

  const groups: Array<{ header: string; keys: string[] }> = [
    { header: '# ── Server ──────────────────────────────────────────────────────────────────', keys: ['NODE_ENV', 'PORT', 'CORS_ORIGIN', 'LOG_LEVEL'] },
    { header: '# ── Security ────────────────────────────────────────────────────────────────', keys: ['CSRF_SECRET', 'ADMIN_API_KEY', 'ALLOWED_EMAIL_DOMAIN'] },
    { header: '# ── Intercom ─────────────────────────────────────────────────────────────────', keys: Object.keys(env).filter(k => k.startsWith('INTERCOM')) },
    { header: '# ── Database ────────────────────────────────────────────────────────────────', keys: ['DATABASE_PATH'] },
    { header: '# ── Uploads ─────────────────────────────────────────────────────────────────', keys: ['MAX_FILE_SIZE_MB', 'MAX_FILES_PER_REQUEST', 'ALLOWED_FILE_TYPES'] },
    { header: '# ── Rate limiting ───────────────────────────────────────────────────────────', keys: ['RATE_LIMIT_WINDOW_MS', 'RATE_LIMIT_MAX_REQUESTS'] },
  ];

  const written = new Set<string>();
  for (const group of groups) {
    const relevant = group.keys.filter(k => k in env);
    if (!relevant.length) continue;
    lines.push(group.header);
    for (const key of relevant) {
      if (comments[key]) lines.push(`# ${comments[key]}`);
      lines.push(`${key}=${env[key]}`);
      written.add(key);
    }
    lines.push('');
  }

  // Any remaining keys not in the groups
  const leftover = Object.keys(env).filter(k => !written.has(k));
  if (leftover.length) {
    lines.push('# ── Other ───────────────────────────────────────────────────────────────────');
    for (const key of leftover) {
      lines.push(`${key}=${env[key]}`);
    }
    lines.push('');
  }

  fs.writeFileSync(envPath, lines.join('\n'));
}

function generateSecret(bytes = 32): string {
  const { randomBytes } = require('crypto');
  return randomBytes(bytes).toString('hex');
}

// ─── Product → Ticket Type matcher ───────────────────────────────────────────

const PRODUCT_KEYWORDS: Record<string, string[]> = {
  'erp-pymes':    ['erp', 'pymes', 'pyme'],
  'restobar':     ['restobar', 'resto', 'bar', 'restaurante', 'restaurant'],
  'pos-tienda':   ['pos', 'tienda', 'punto de venta', 'store'],
  'nomina':       ['nomina', 'nómina', 'payroll', 'rrhh', 'hr'],
  'alojamientos': ['alojamiento', 'hotel', 'hospedaje', 'accommodation'],
  'enterprise':   ['enterprise', 'empresarial', 'corporativo'],
};

function matchTicketTypeToProduct(ticketType: TicketType): string | null {
  const nameLower = ticketType.name.toLowerCase();
  const descLower = (ticketType.description ?? '').toLowerCase();
  const combined = `${nameLower} ${descLower}`;

  for (const [product, keywords] of Object.entries(PRODUCT_KEYWORDS)) {
    if (keywords.some(kw => combined.includes(kw))) {
      return product;
    }
  }
  return null;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n🔍 Loggro Incidents Portal — Intercom Discovery\n');
  console.log('═'.repeat(60));

  const ENV_PATH = path.resolve(__dirname, '../../.env');
  const existingEnv = readEnv(ENV_PATH);

  // ── 1. Token validation ───────────────────────────────────────────────────
  console.log('\n▶  1/7  Validating access token…');
  let adminInfo: { admin_id: string; name: string; email: string };
  try {
    adminInfo = await validateToken();
    console.log(`   ✅ Token valid`);
    console.log(`   👤 Authenticated as: ${adminInfo.name} <${adminInfo.email}>`);
    console.log(`   🆔 Admin ID: ${adminInfo.admin_id}`);
  } catch (err: unknown) {
    const status = (err as { response?: { status?: number } }).response?.status;
    if (status === 401) {
      console.error('   ❌ Token invalid (401 Unauthorized). Check INTERCOM_ACCESS_TOKEN.');
    } else {
      console.error(`   ❌ API error: ${(err as Error).message}`);
    }
    process.exit(1);
  }

  // ── 2. Workspace info ─────────────────────────────────────────────────────
  console.log('\n▶  2/7  Fetching workspace info…');
  let workspace: Workspace;
  try {
    workspace = await getWorkspace();
    const app = (workspace as unknown as Record<string, unknown>);
    const ws = {
      id: (app.app_id ?? app.id ?? workspace.id) as string,
      name: (app.name ?? workspace.name) as string,
      region: (app.region ?? workspace.region ?? 'unknown') as string,
      timezone: (app.timezone ?? workspace.timezone ?? 'unknown') as string,
    };
    console.log(`   ✅ Workspace: ${ws.name}`);
    console.log(`   🌍 Region: ${ws.region}`);
    console.log(`   🕐 Timezone: ${ws.timezone}`);
    console.log(`   🆔 Workspace ID: ${ws.id}`);
    existingEnv['INTERCOM_WORKSPACE_ID'] = ws.id;
    existingEnv['INTERCOM_WORKSPACE_NAME'] = ws.name;
  } catch (err) {
    console.warn(`   ⚠  Could not fetch workspace details: ${(err as Error).message}`);
  }

  // ── 3. Ticket Types ───────────────────────────────────────────────────────
  console.log('\n▶  3/7  Discovering Ticket Types…');
  let ticketTypes: TicketType[] = [];
  try {
    ticketTypes = await getTicketTypes();
    const active = ticketTypes.filter(t => !t.archived);
    console.log(`   ✅ Found ${active.length} active ticket type(s) (${ticketTypes.length - active.length} archived)`);

    const envKeyMap: Record<string, string> = {
      'erp-pymes':    'INTERCOM_TICKET_TYPE_ERP_PYMES',
      'restobar':     'INTERCOM_TICKET_TYPE_RESTOBAR',
      'pos-tienda':   'INTERCOM_TICKET_TYPE_POS_TIENDA',
      'nomina':       'INTERCOM_TICKET_TYPE_NOMINA',
      'alojamientos': 'INTERCOM_TICKET_TYPE_ALOJAMIENTOS',
      'enterprise':   'INTERCOM_TICKET_TYPE_ENTERPRISE',
    };

    const matched: Record<string, string> = {};
    const unmatched: TicketType[] = [];

    for (const tt of active) {
      const product = matchTicketTypeToProduct(tt);
      if (product) {
        matched[product] = tt.id;
        console.log(`   🎯 ${tt.name} (id: ${tt.id}) → ${product}`);
      } else {
        unmatched.push(tt);
        console.log(`   ❓ ${tt.name} (id: ${tt.id}) → no product match`);
      }
    }

    // Write matched ones to env
    for (const [product, id] of Object.entries(matched)) {
      existingEnv[envKeyMap[product]] = id;
    }

    // For unmatched, show them so the user can manually assign if needed
    if (unmatched.length > 0) {
      console.log('\n   📋 Unmatched ticket types (set manually if needed):');
      for (const tt of unmatched) {
        console.log(`      • "${tt.name}" → ID: ${tt.id}`);
        console.log(`        Add to .env: INTERCOM_TICKET_TYPE_<PRODUCT>=${tt.id}`);
      }
    }

    // If NO ticket types exist yet, note it
    if (active.length === 0) {
      console.log('\n   ⚠  No ticket types found in this workspace.');
      console.log('   📌 Create them at: https://app.intercom.com/a/apps/_/settings/tickets');
      console.log('   📌 Suggested names: ERP Pymes, Restobar, POS Tienda, Nómina, Alojamientos, Enterprise');
      console.log('   Then re-run: npm run intercom:discover');
    }

    // Write all ticket types as JSON for reference
    const allIds = active.map(t => ({ id: t.id, name: t.name, archived: t.archived }));
    existingEnv['INTERCOM_TICKET_TYPES_JSON'] = JSON.stringify(allIds);

  } catch (err) {
    console.warn(`   ⚠  Could not fetch ticket types: ${(err as Error).message}`);
  }

  // ── 4. Ticket Type Attributes ─────────────────────────────────────────────
  console.log('\n▶  4/7  Fetching Ticket Type attributes…');
  const allAttributes: Record<string, TicketAttribute[]> = {};
  for (const tt of ticketTypes.filter(t => !t.archived)) {
    const attrs = await getTicketTypeAttributes(tt.id);
    if (attrs.length > 0) {
      allAttributes[tt.id] = attrs;
      const attrNames = attrs.map(a => `${a.name} (${a.data_type}${a.required_to_create ? ', required' : ''})`).join(', ');
      console.log(`   📎 ${tt.name}: ${attrNames}`);
    } else {
      console.log(`   📎 ${tt.name}: no custom attributes`);
    }
  }

  // ── 5. Teams ─────────────────────────────────────────────────────────────
  console.log('\n▶  5/7  Discovering Teams (Inboxes)…');
  try {
    const teams = await getTeams();
    if (teams.length > 0) {
      console.log(`   ✅ Found ${teams.length} team(s):`);
      for (const t of teams) {
        console.log(`      • ${t.name} (id: ${t.id})`);
      }
      existingEnv['INTERCOM_TEAMS_JSON'] = JSON.stringify(teams.map(t => ({ id: t.id, name: t.name })));

      // Auto-set default inbox from first team
      if (!existingEnv['INTERCOM_DEFAULT_INBOX_ID'] && teams[0]) {
        existingEnv['INTERCOM_DEFAULT_INBOX_ID'] = teams[0].id;
        console.log(`   ℹ  Default inbox set to: ${teams[0].name} (${teams[0].id})`);
      }
    } else {
      console.log('   ⚠  No teams found. Tickets will go to the default inbox.');
    }
  } catch (err) {
    console.warn(`   ⚠  Could not fetch teams: ${(err as Error).message}`);
  }

  // ── 6. Custom Data Attributes ─────────────────────────────────────────────
  console.log('\n▶  6/7  Fetching Custom Data Attributes…');
  try {
    const convAttrs = await getConversationAttributes();
    const contactAttrs = await getContactAttributes();

    const customConv = convAttrs.filter(a => a.full_name?.startsWith('custom_attributes.'));
    const customContact = contactAttrs.filter(a => a.full_name?.startsWith('custom_attributes.'));

    if (customConv.length > 0) {
      console.log(`   💬 Conversation custom attributes (${customConv.length}):`);
      for (const a of customConv) {
        const opts = a.options?.map(o => o.value).join(', ');
        console.log(`      • ${a.label} [${a.data_type}]${opts ? ` — options: ${opts}` : ''}`);
      }
    } else {
      console.log('   💬 No conversation custom attributes');
    }

    if (customContact.length > 0) {
      console.log(`   👤 Contact custom attributes (${customContact.length}):`);
      for (const a of customContact) {
        console.log(`      • ${a.label} [${a.data_type}]`);
      }
    } else {
      console.log('   👤 No contact custom attributes');
    }
  } catch (err) {
    console.warn(`   ⚠  Could not fetch custom attributes: ${(err as Error).message}`);
  }

  // ── 7. Admins ─────────────────────────────────────────────────────────────
  console.log('\n▶  7/7  Listing workspace admins…');
  try {
    const admins = await getAdmins();
    console.log(`   ✅ ${admins.length} admin(s) in workspace:`);
    for (const a of admins) {
      const isMe = a.id === adminInfo.admin_id;
      console.log(`      • ${a.name} <${a.email}>${isMe ? ' ← (token owner)' : ''}`);
    }
  } catch (err) {
    console.warn(`   ⚠  Could not fetch admins: ${(err as Error).message}`);
  }

  // ── Ensure required non-Intercom values are populated ─────────────────────
  if (!existingEnv['INTERCOM_ACCESS_TOKEN']) {
    existingEnv['INTERCOM_ACCESS_TOKEN'] = TOKEN!;
  }
  if (!existingEnv['INTERCOM_API_VERSION']) {
    existingEnv['INTERCOM_API_VERSION'] = '2.11';
  }
  if (!existingEnv['NODE_ENV']) {
    existingEnv['NODE_ENV'] = 'development';
  }
  if (!existingEnv['PORT']) {
    existingEnv['PORT'] = '3001';
  }
  if (!existingEnv['CORS_ORIGIN']) {
    existingEnv['CORS_ORIGIN'] = 'http://localhost:5173';
  }
  if (!existingEnv['ALLOWED_EMAIL_DOMAIN']) {
    existingEnv['ALLOWED_EMAIL_DOMAIN'] = 'loggro.com';
  }
  if (!existingEnv['DATABASE_PATH']) {
    existingEnv['DATABASE_PATH'] = './data/portal.db';
  }
  if (!existingEnv['MAX_FILE_SIZE_MB']) {
    existingEnv['MAX_FILE_SIZE_MB'] = '10';
  }
  if (!existingEnv['MAX_FILES_PER_REQUEST']) {
    existingEnv['MAX_FILES_PER_REQUEST'] = '5';
  }
  if (!existingEnv['RATE_LIMIT_WINDOW_MS']) {
    existingEnv['RATE_LIMIT_WINDOW_MS'] = '900000';
  }
  if (!existingEnv['RATE_LIMIT_MAX_REQUESTS']) {
    existingEnv['RATE_LIMIT_MAX_REQUESTS'] = '5';
  }
  if (!existingEnv['LOG_LEVEL']) {
    existingEnv['LOG_LEVEL'] = 'info';
  }

  // Generate secrets if missing or still defaults
  const defaultCsrf = 'dev-csrf-secret-change-in-production-min32chars!!';
  const defaultAdmin = 'dev-admin-key-change-in-production';
  if (!existingEnv['CSRF_SECRET'] || existingEnv['CSRF_SECRET'] === defaultCsrf) {
    existingEnv['CSRF_SECRET'] = generateSecret(32);
    console.log('\n   🔑 Generated new CSRF_SECRET');
  }
  if (!existingEnv['ADMIN_API_KEY'] || existingEnv['ADMIN_API_KEY'] === defaultAdmin) {
    existingEnv['ADMIN_API_KEY'] = generateSecret(24);
    console.log('   🔑 Generated new ADMIN_API_KEY');
  }

  // ── Write .env ─────────────────────────────────────────────────────────────
  const comments: Record<string, string> = {
    'INTERCOM_ACCESS_TOKEN': 'Intercom personal access token',
    'INTERCOM_WORKSPACE_ID': 'Auto-discovered',
    'INTERCOM_TICKET_TYPES_JSON': 'Auto-discovered — all active ticket types (JSON)',
    'INTERCOM_TEAMS_JSON': 'Auto-discovered — all teams (JSON)',
    'INTERCOM_DEFAULT_INBOX_ID': 'Auto-discovered — first team ID used as default inbox',
    'CSRF_SECRET': 'Auto-generated — rotate periodically',
    'ADMIN_API_KEY': 'Auto-generated — keep secret',
  };

  writeEnv(ENV_PATH, existingEnv, comments);

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('\n' + '═'.repeat(60));
  console.log('✅  Discovery complete — .env updated\n');
  console.log(`📄 File: ${ENV_PATH}`);

  // Show which ticket types are missing
  const productKeys = [
    ['erp-pymes',    'INTERCOM_TICKET_TYPE_ERP_PYMES'],
    ['restobar',     'INTERCOM_TICKET_TYPE_RESTOBAR'],
    ['pos-tienda',   'INTERCOM_TICKET_TYPE_POS_TIENDA'],
    ['nomina',       'INTERCOM_TICKET_TYPE_NOMINA'],
    ['alojamientos', 'INTERCOM_TICKET_TYPE_ALOJAMIENTOS'],
    ['enterprise',   'INTERCOM_TICKET_TYPE_ENTERPRISE'],
  ];

  const missing = productKeys.filter(([, k]) => !existingEnv[k]);
  if (missing.length > 0) {
    console.log('\n⚠  Missing Ticket Type IDs (create them in Intercom then re-run):');
    for (const [product] of missing) {
      console.log(`   • ${product}`);
    }
    console.log('\n   👉 https://app.intercom.com/a/apps/_/settings/tickets');
    console.log('   👉 Then run: npm run intercom:discover\n');
  } else {
    console.log('\n✅  All 6 product ticket types mapped!\n');
  }

  // Show ADMIN_API_KEY so user can save it
  if (existingEnv['ADMIN_API_KEY']) {
    console.log(`🔑 ADMIN_API_KEY (save this): ${existingEnv['ADMIN_API_KEY']}`);
  }
  console.log('');
}

main().catch((err) => {
  console.error('\n❌ Discovery failed:', err.message);
  process.exit(1);
});
